@url = https://admin.j2y.localhost:5003

###
POST {{url}}
Content-Type: application/json

{
    "environment": {},
"enabled": true,
    "continueOnError": false,
    "alwaysRun": false,
    "displayName": "PowerShell Script",
    "timeoutInMinutes": 0,
    "condition": "succeeded()",
    "refName": "PowerShell1",
    "task": {
        "id": "e213ff0f-5d5c-4791-802d-52ea3e7be1f1",
        "versionSpec": "1.*",
        "definitionType": "task"
    },
    "inputs": {
        "scriptType": "filePath",
        "scriptName": "./build.ps1",
        "arguments": "",
        "workingFolder": "",
        "inlineScript": "",
        "failOnStandardError": "true"
    }
}

###
POST https://admin.j2y.localhost:5003
Content-Type: application/yaml

---
environment: {}
enabled: true
continueOnError: false
alwaysRun: false
displayName: PowerShell Script
timeoutInMinutes: 0
condition: succeeded()
refName: PowerShell1
task:
  id: e213ff0f-5d5c-4791-802d-52ea3e7be1f1
  versionSpec: 1.*
  definitionType: task
inputs:
  scriptType: filePath
  scriptName: "./build.ps1"
  arguments: ""
  workingFolder: ""
  inlineScript: ""
  failOnStandardError: "true"

###
curl --header "Content-Type: application/json" --request POST -k --data @test.json {{url}}

###
curl --header "Content-Type: application/yaml" --request POST -k --data @test.yml {{url}}